Reverse tunnel feature Specify options without requiring SSH config (for dropbear, which doesn't support SSH config) Remove suckblow requirement, add `nc` functionality or builtin checking with dropbear (`-K` option) rewrite of install.sh to add new options ps command flag refined determination SSH flag determination refined all tabs to spaces remove C code remove `rstunneld`, substitute with `-d` option in main executable this commit is kinda messy, there will need to be some cleanup

diff --git a/rstunnel b/rstunnel
--- a/rstunnel
+++ b/rstunnel
@@ -10,12 +10,15 @@
 ##			Jay Goldberg - jaymgoldberg@gmail.com
 
 LoadConfig() {
-    if [ ! -x ./rstunnel.conf ]; then
-        echo "[FATAL] Can't find rstunnel.conf. Run install.sh to generate rstunnel.conf";
+    DebugMsg ">> Loading config file"
+    if [ ! -f ./rstunnel.conf ]; then
+        echo "[FATAL] Can't find rstunnel.conf. Run install.sh to generate rstunnel.conf"
+        echo "or cd into your rstunnel installation directory"
         exit 1
     else
         . ./rstunnel.conf
     fi
+    DebugMsg ">> Config file loaded"
 }
 
 # error check function
@@ -45,6 +48,8 @@ Usage() {
       [-v/-vv]  '-v' is VERBOSE output, ' is VERBOSE output, '-vv' is DEBUG output. It is
             not reccomended that you run in DEBUG mode when running in cron as there is
             quite a lot of output
+            
+      [-d]  Daemonize, run in a constant watch loop
 
       [-?]  This help message
 HEREDOC
@@ -52,6 +57,7 @@ HEREDOC
 }
 
 CheckOS() {
+    DebugMsg ">> Checking OS"
     case $(uname) in
         SunOS)
             OS='SunOS'
@@ -76,86 +82,268 @@ MailUser() {
         echo "to the current working directory with your message written in the file."
         exit 1
     fi
+
     # E-mail User, saying the tunnel was down, and now restarted.
-	for emailuser in $EMAIL; do
-		mail -s "Tunnel_Restarted" $emailuser < mail.message
-		echo "";
-		echo "Mail Sent: "$emailuser
-	done  
+    for emailuser in $EMAIL; do
+        mail -s "Tunnel_Restarted" $emailuser < mail.message
+        echo "";
+        echo "Mail Sent: "$emailuser
+    done  
 }
 
 TunRun() {
-    DebugMsg ">> running command \"$SSHPATH $SSHFLAGS $REMOTEHOSTNAME sleep 99999999999\""
-	$SSHPATH $SSHFLAGS $REMOTEHOSTNAME sleep 99999999999
+    DebugMsg ">> running command \"$SSHPATH $SSHFLAGS ${REMOTEUSER}@$REMOTEHOSTNAME sleep 99999999999\""
+    $SSHPATH $SSHFLAGS ${REMOTEUSER}@$REMOTEHOSTNAME sleep 99999999999
+}
+
+TunKill() {
+    DebugMsg ">> Killing SSH process"
+
+    ${KILLCMD}
+    ERR=$?
+
+    if [ $ERR -ne 0 ]; then
+        echo "[FATAL] Unable to kill the tunnel process";
+        exit 1
+    fi
+}
+
+SetConfig() {
+    DebugMsg ">> Setting variables"
+    if [ ! -z $REVERSEPORT ]; then
+        DebugMsg ">> configuring in reverse mode"
+        LOCALPORT=${LOCALPORT:-22}
+        REMOTEIP=${REMOTEIP:-localhost}
+        MODE=reverse
+    elif [[ ! -z $CHECKPORT || ! -z $REMOTEIP || ! -z $REMOTEPORT ]]; then
+        unset CONFIGFILE
+        return
+    else
+        # Let's try to get all the paramaters out of the ssh configfile
+        if [ ! -z "$CONFIGFILE" -a -f "$CONFIGFILE" ]; then
+            DebugMsg ">> Parsing SSH config"
+            CHECKPORT=$(grep "LocalForward" $CONFIGFILE | grep -v "#" | sed -e s/=/\ /g | awk '{print $2}')
+            REMOTEIP=$(grep "LocalForward" $CONFIGFILE | grep -v "#" | sed -e s/=/\ /g | awk '{print $3}' | awk -F':' '{print $1}')
+            REMOTEPORT=$(grep "LocalForward" $CONFIGFILE | grep -v "#" | sed -e s/=/\ /g | awk '{print $3}' | awk -F':' '{print $2}')
+        elif [[ -z $CHECKPORT || -z $REMOTEIP || -z $REMOTEPORT ]]; then
+            echo "[FATAL] Can't find $CONFIGFILE and CHECKPORT, REMOTEIP and REMOTEPORT are not defined in rstunnel.conf"
+        fi
+
+        # We have to make sure that we set aside a special port for netcat on
+        # the same tunnel as a true test of the connectivity requires we send
+        # some data through throught it using netcat
+        grep "LocalForward $CHECKPORT $REMOTEIP:$REMOTEPORT" $CONFIGFILE > tempfile.out
+
+        if [ -s tempfile.out ]; then
+            echo -n ""
+        else
+            if [[ -z $CHECKPORT || -z $REMOTEIP || -z $REMOTEPORT ]] ; then
+                # Let's confirm with the user that we are going to add in a "LocalForward" line
+                # in the ~/.ssh/config.
+                echo "[FATAL] Can't find LocalForward for RSTunnel."
+                echo -n "Do you want me to add it in the config file for you? [y/n] > "
+                read value
+                while [ -z $value ]; do
+                    echo -n "Invalid selection. Please select [y/n] > "
+                    read value
+                done
+
+                if [ $value = "y" ]; then
+                    if [ -w "$CONFIGFILE" ]; then
+                        echo "## ADDED BY: RSTunnel " >> "$CONFIGFILE"
+                        echo "LocalForward "$CHECKPORT" "$REMOTEIP":"$REMOTEPORT >> "$CONFIGFILE"
+                        echo "Added: LocalForward "$CHECKPORT" "$REMOTEIP":"$REMOTEPORT
+                        sleep 2
+                    else
+                        echo "[FATAL] Unable to write to file: "$CONFIGFILE
+                        echo "Make sure the line 'LocalForward $CHECKPORT $REMOTEIP:$REMOTEPORT' is added to your $CONFIGFILE"
+                        exit 1
+                    fi
+                else
+                    echo "Make sure the line 'LocalForward $CHECKPORT $REMOTEIP:$REMOTEPORT' is added to your $CONFIGFILE"
+                    exit 1
+                fi
+            fi
+		fi
+	fi
 }
 
 # test the connection through the tunnel
 TestConnection() {
-	local NETWAIT=10
-    
-    timeout 10 echo "Testing Connection" | nc $FLAGS localhost $CHECKPORT 2>&1 >/dev/null
+    if [ ! -z $TESTCONNECTION ]; then
+        DebugMsg ">> No connection test needed for dropbear SSH client"
+        return
+    fi
+	
+    DebugMsg ">> running command \"echo \"Testing Connection\" | nc $NCFLAGS localhost $CHECKPORT\""
+    echo "Testing Connection" | nc $NCFLAGS localhost $CHECKPORT 2>&1 >/dev/null
     ERR=$?
     
     if [ $ERR -ne 0 ]; then 
-		DebugMsg ">> [ F A I L E D ]"
-		DebugMsg "===> Attempting to restart tunnel"
-		DebugMsg ">> Killing Old SSH Process"
-		
-		${KILLCMD} | ${SHELLPATH}; ERR=$?
-		
-		if [ $ERR -ne 0 ]; then
-			echo "[FATAL] Unable to kill previous process";
-			exit 1
-		fi
+        DebugMsg ">> [ F A I L E D ]"
+        DebugMsg ">> Do you have a check port defined in your SSH config?"
+        DebugMsg "===> Attempting to restart tunnel"
 
-		TunRun
+        TunKill
+
+        TunRun
 	  
-		ErrorCheck
+        ErrorCheck
 		
-		if [ ! -z $X_EMAIL ]; then	
-			MailUser
-		fi
+        if [ ! -z $X_EMAIL ]; then	
+            MailUser
+        fi
     fi
 }
 
 SetFlags() {
-	NCFLAGS="-w $NETWAIT -q 1 -i 1"
-	SSHFLAGS="-n -f -F $CONFIGFILE"
+    DebugMsg ">> Setting command options"
+    SSHFLAGS="-N -f"
+    NCFLAGS="-w 5"
+
+    # reverse tunnel mode
+    if [ "$MODE" == "reverse" ]; then
+        # TODO dynamic grab of remote port using web service, though
+        # this should be done with a separate flag for mode and a flag
+        # for allowing remote lookup
+        SSHFLAGS="$SSHFLAGS -R ${REVERSEPORT}:${REMOTEIP}:${LOCALPORT}"
+    else
+        SSHFLAGS="$SSHFLAGS -L ${CHECKPORT}:${REMOTEIP}:${REMOTEPORT}"
+    fi
+	
+	# check for dropbear
+    local realssh=$(basename $(readlink -f $(which ssh)))
+    if [ "$realssh" == "dropbearmulti" -o "$realssh" == "dropbear" ]; then
+        SSHFLAGS="$SSHFLAGS -i $IDENTITYFILE -K $KEEPALIVE -y"
+        TESTCONNECTION=false
+    elif [ -z $CONFIGFILE ]; then
+        # TODO use builtin keepalive on real OpenSSH client? (-o ServerAliveInterval=5)
+        # or -o StrictHostKeyChecking=off
+        #TESTCONNECTION=false
+        SSHFLAGS="$SSHFLAGS -n -i $IDENTITYFILE"
+    else
+        SSHFLAGS="$SSHFLAGS -n -F $CONFIGFILE"
+    fi
+	
+	# check for type of netcat
+    if [ "$(basename $(readlink -f $(which nc)))" == "busybox" ]; then
+        NCFLAGS="-w 5 -q 1 -i 1"
+    fi
 	
 	# check what kind of OS is running to determine the flags for the "ps" command
-	if [ $OS = "FreeBSD" -o $OS = "Linux" ]; then
-		PSFLAGS="-awx"
-		KILLCMD=$(ps $PSFLAGS | grep ssh | grep "$REMOTEHOSTNAME sleep" | awk '{print "kill -9 "$1}')
-		[ -z $CONFIGFILE ] && CONFIGFILE=~/.ssh/config
-	elif [ $OS = "SunOS" ]; then
-		PSFLAGS="-ewf"
-		KILLCMD=$(ps $PSFLAGS | grep ssh | grep "$REMOTEHOSTNAME sleep" | awk '{print "kill -9 "$2}')
-		[ -z $CONFIGFILE ] && CONFIGFILE=~/.ssh/config
-	else 
-		echo "[FATAL] Sorry, your OS is not supported."
-		exit 1
-	fi
-	
-	[ ! -z $DEBUG ] && ( NCFLAGS="$FLAGS -v"; SSHFLAGS="$SSHFLAGS -vvv" )
+    if [ $OS = "FreeBSD" -o $OS = "Linux" ]; then
+        PSFLAGS="-awx"
+        [ "$(basename $(readlink -f $(which ps)))" == "busybox" ] && PSFLAGS="-w"
+        KILLCMD=$(ps $PSFLAGS | grep ssh | grep "$REMOTEHOSTNAME sleep" | awk '{print "kill -9 "$1}')
+    elif [ $OS = "SunOS" ]; then
+        PSFLAGS="-ewf"
+        KILLCMD=$(ps $PSFLAGS | grep ssh | grep "$REMOTEHOSTNAME sleep" | awk '{print "kill -9 "$2}')
+    else 
+        echo "[FATAL] Sorry, your OS is not supported."
+        exit 1
+    fi
+
+    [ ! -z $DEBUG ] && ( NCFLAGS="$NCFLAGS -v"; SSHFLAGS="$SSHFLAGS -vvv" )
 }
 
 DebugMsg() {
-	local msg="$1"
-	[ $VERBOSE ] && echo "$msg"
+    local msg="$1"
+    [ $VERBOSE ] && echo "$msg"
+}
+
+Cleanup() {
+    DebugMsg "===> Cleaning up"
+
+    TunKill
+
+    rm -f tempfile.out
+    rm -f temp.out
+
+    exit
+}
+
+Main() {
+    DebugMsg "===> Doing some preliminary checks"
+
+    CheckOS
+    SetConfig
+    SetFlags
+
+    # check that required binaries are available
+    for cmd in "ssh" ; do
+        if [ ! $(which $cmd) ]; then
+            echo "[FATAL] Can't find $cmd, make sure the required binaries are installed and that their paths in the config are correct"
+            exit 1
+        fi
+    done
+
+    # TODO what about nc in conjunction with busybox?
+
+    # check the proc listing for a active SSH tunnel running
+    ps $PSFLAGS | grep ssh | grep $REMOTEHOSTNAME | grep -v "grep "$REMOTEHOSTNAME | grep -v "sshd" > temp.out
+
+    if [ -s temp.out ]; then
+        DebugMsg  "===> Tunnel appears to be up"
+        DebugMsg  ">> Testing connection for $REMOTEHOSTNAME"
+
+        # try to make a connection through the ssh forwarding port.
+        TestConnection
+
+        DebugMsg "===> Tunnel is still up and running"
+    else 
+        DebugMsg "===> Tunnel doesn't appear to be up"
+        DebugMsg ">> Attempting to start tunnel"
+
+        TunRun
+
+        ErrorCheck
+
+        [ ! -z $X_EMAIL ] && MailUser
+
+        DebugMsg ">> Testing connection for $REMOTEHOSTNAME"
+
+        TestConnection
+        sleep 1 # TODO: why sleep here?
+
+        DebugMsg "===> Tunnel is up and running"
+    fi
+}
+
+Daemonize() {
+    local counter=1
+    local last_count=$KEEPALIVE
+
+    trap Cleanup SIGINT
+
+    while true; do
+        while [ $counter -lt $last_count ]; do
+            let counter=$counter+1
+            sleep 1
+            if [ $counter -eq $last_count ]; then
+                counter=1
+                sleep 2
+                echo $(date)" "$HOSTNAME": RSTunnel daemon starting" >> $logfile
+                Main
+            fi
+        done
+    done
 }
 
 for arg in $1 $2; do
     case $arg in
         -v)
-            VERBOSE=on
+            VERBOSE=true
             ;;
         -vv)
-            VERBOSE=on
-            DEBUG=on
-            echo "===>  DEBUGING ON  <==="
+            VERBOSE=true
+            DEBUG=true
+            DebugMsg "===>  DEBUGING ON  <==="
             ;;
         -e)
-            X_EMAIL=on
+            X_EMAIL=true
+            ;;
+        -d)
+            DAEMONIZE=true
             ;;
         -?)
             Usage
@@ -165,98 +353,8 @@ done
 
 LoadConfig
 
-DebugMsg "===> Doing some preliminary checks"
-
-CheckOS
-
-SetFlags
-
-# check that required binaries are available
-for cmd in "nc" "sh" "ssh" ; do
-    if [ ! $(command -v $cmd) ]; then
-        echo "[FATAL] Can't find $cmd, make sure the required binaries are installed and that their paths in the config are correct"
-        exit 1
-    fi
-done
-
-# Let's get all the perameters out of the ssh configfile
-if [ -f "$CONFIGFILE" ]; then
-    LOCALPORT=$(grep "LocalForward" $CONFIGFILE | grep -v "#" | sed -e s/=/\ /g | awk '{print $2}')
-    REMOTEIP=$(grep "LocalForward" $CONFIGFILE | grep -v "#" | sed -e s/=/\ /g | awk '{print $3}' | awk -F':' '{print $1}')
-    REMOTEPORT=$(grep "LocalForward" $CONFIGFILE | grep -v "#" | sed -e s/=/\ /g | awk '{print $3}' | awk -F':' '{print $2}')
+if [ ! -z $DAEMONIZE ]; then
+    Daemonize
 else
-    echo "[FATAL] Can't find "$CONFIGFILE
-    exit 1
+    Main
 fi
-
-# We have to make sure that we set aside a special port for netcat on
-# the same tunnel as a true test of the connectivity requires we send
-# some data through throught it using netcat
-grep "LocalForward $CHECKPORT $REMOTEIP:$REMOTEPORT" $CONFIGFILE > tempfile.out
-
-if [ -s tempfile.out ]; then
-    echo -n ""
-else
-    # Let's confirm with the user that we are going to add in a "LocalForward" line
-    # in the ~/.ssh/config.
-    echo "[FATAL] Can't find LocalForward for RSTunnel."
-    echo -n "Do you want me to add it in the config file for you? [y/n] > "
-    read value
-    while [ -z $value ]; do
-        echo -n "Invalid selection. Please select [y/n] > "
-        read value
-    done
-
-    if [ $value = "y" ]; then
-        if [ -w "$CONFIGFILE" ]; then
-            echo "## ADDED BY: RSTunnel " >> "$CONFIGFILE"
-            echo "LocalForward "$CHECKPORT" "$REMOTEIP":"$CHECKPORT >> "$CONFIGFILE"
-            echo "Added: LocalForward "$CHECKPORT" "$REMOTEIP":"$CHECKPORT
-            sleep 2
-
-            else
-            echo "[FATAL] Unable to write to file: "$CONFIGFILE
-            echo "Make sure the line 'LocalForward $CHECKPORT $REMOTEIP:$CHECKPORT' is added to your $CONFIGFILE"
-            exit 1
-        fi
-    else
-        echo "Make sure the line 'LocalForward $CHECKPORT $REMOTEIP:$CHECKPORT' is added to your $CONFIGFILE"
-        exit 1
-    fi
-fi
-
-# check the proc listing for a active SSH tunnel running
-ps $PSFLAGS | grep ssh | grep $REMOTEHOSTNAME | grep -v "grep "$REMOTEHOSTNAME | grep -v "sshd" > temp.out
-
-if [ -s temp.out ]; then
-	  DebugMsg  "===> Tunnel appears to be up"
-	  DebugMsg  ">> Testing connection for $REMOTEHOSTNAME"
-
-    # try to make a connection through the ssh forwarding port.
-    TestConnection
-
-    DebugMsg "===> Tunnel is still up and running"
-else 
-    DebugMsg "===> Tunnel doesn't appear to be up"
-    DebugMsg ">> Attempting to start tunnel"
-    
-    TunRun
-        
-    ErrorCheck
-    
-    if [ ! -z $X_EMAIL ]; then
-        MailUser
-    fi
-    
-    DebugMsg ">> Testing connection for $REMOTEHOSTNAME"
-    
-    TestConnection
-    sleep 1 # TODO: why sleep here?
-    
-    DebugMsg "===> Tunnel is up and running"
-fi
-
-[ ! -z $VERBOSE ] && echo "===> Cleaning up"
-
-rm -f tempfile.out
-rm -f temp.out
